spring:
  application:
    name: Kotlin-Board
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: pwd
    url: jdbc:mysql://localhost:3306/kotlin_board?useSSL=false&serverTimezone=Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
